# Base image
FROM ubuntu:focal

# Update package list
RUN apt-get update && \
    apt-get install -y openssh-server sudo passwd

# Create vagrant user and set up SSH access
RUN useradd -m vagrant && \
    echo "vagrant:vagrant" | chpasswd && \
    usermod -aG sudo vagrant && \
    mkdir /home/vagrant/.ssh && \
    chmod 700 /home/vagrant/.ssh


ADD https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub /home/vagrant/.ssh/authorized_keys



# Copy SSH public key (if you have one)
#COPY id_rsa.pub /home/vagrant/.ssh/authorized_keys
RUN chmod 600 /home/vagrant/.ssh/authorized_keys

# Set up SSH server configuration
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Expose SSH port and set volume for cgroup
EXPOSE 22
VOLUME ["/sys/fs/cgroup"]

# Ensure services are started on boot
RUN systemctl enable sshd.service

# Start SSH server
CMD ["sshd", "-D"]
