Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "dst-linux-disk"
  
  config.vm.boot_timeout = 600

  config.vm.provider "virtualbox" do |vb|
    vb.name = "dst-linux-disk"
    vb.gui = false
    vb.memory = 8024
    vb.cpus = 4
  end
end
