
(2..3).each do |i| #At each iteration of the loop, the variable i takes a value from 2 to 3
  Vagrant.configure("2") do |config|
    # Define the admin {i} VM
    config.vm.define "admin#{i-1}" do |admin|
      admin.vm.hostname = "admin#{i-1}"
      admin.vm.provider "docker" do |dockeradmin|
        dockeradmin.image = "datascientest:vagrant6"
        dockeradmin.create_args = [
          "--cpuset-cpus=1",
          "--memory=1g"
        ]
      end
      admin.vm.network "private_network", ip: "192.168.1.#{i}", netmask: 24
      admin.vm.network "private_network", ip: "192.168.2.#{i}", netmask: 24
      admin.vm.network "forwarded_port", guest: 443, host: "#{i}443"
    end
  end
end

(4..5).each do |i| #At each iteration of the loop, the variable i takes a value from 4 to 5
  Vagrant.configure("2") do |config|
    # Define the admin {i} VM
    config.vm.define "client1#{i}" do |client1|
      client1.vm.hostname = "client1#{i}"
      client1.vm.provider "docker" do |dockerclient1|
        dockerclient1.image = "datascientest:vagrant6"
        dockerclient1.create_args = [
          "--cpuset-cpus=1",
          "--memory=1g"
        ]
      end
      client1.vm.network "private_network", ip: "192.168.1.1#{i}", netmask: 24
    end
  end
end

(4..5).each do |i| #At each iteration of the loop, the variable i takes a value from 4 to 5
  Vagrant.configure("2") do |config|
    # Define the admin {i} VM
    config.vm.define "client2#{i}" do |client2|
      client2.vm.hostname = "client2#{i}"
      client2.vm.provider "docker" do |dockerclient2|
        dockerclient2.image = "datascientest:vagrant6"
        dockerclient2.create_args = [
          "--cpuset-cpus=1",
          "--memory=1g"
        ]
      end
      client2.vm.network "private_network", ip: "192.168.2.1#{i}", netmask: 24
    end
  end
end