Vagrant.configure("2") do |config|
  
  config.vm.box = "hashicorp/bionic64"

  config.vm.hostname = "dst-linux-disk"
  
  config.vm.boot_timeout = 600

  config.vm.provider "virtualbox" do |vb|
    vb.name = "dst-linux-disk"
    vb.gui = false
    vb.memory = 8024
    vb.cpus = 4

    # Create disk only if not present
    disk_path = File.join(File.dirname(__FILE__), "extra_disk.vdi")
    unless File.exist?(disk_path)
      puts "==> Creating additional disk at #{disk_path}"
      system("VBoxManage createhd --filename \"#{disk_path}\" --size 10240 --format VDI")
    end

    # # Use 'post-boot' style customizations so controller exists
    # vb.customize ["storagectl", :id,
    #               "--name", "SATA Controller",
    #               "--add", "sata",
    #               "--controller", "IntelAhci"]

    vb.customize ["storageattach", :id,
                  "--storagectl", "SATA Controller",
                  "--port", 1,
                  "--device", 0,
                  "--type", "hdd",
                  "--medium", disk_path]
  end
end
