names = ['Anthony', 'Alban', 'Lewis', 'Charles']
i = 1

names.each do |name|
  puts "#{i}. #{name}"
  i += 1
end


# clients=4 
# (1..clients).each do |i| #At each iteration of the loop, the variable i takes a value from 1 to 4
#   Vagrant.configure("2") do |config|
#     # Define the client {i} VM
#     config.vm.define "client#{i}" do |client|
#       client.vm.hostname = "client#{i}"
#       client.vm.provider "docker" do |server_1|
#         server_1.image = "datascientest:vagrant6"
#         server_1.create_args = [
#           "--cpuset-cpus=1",
#           "--memory=1g"
#         ]
#       end
#       client.vm.network "private_network", ip: "192.168.1.1#{i}", netmask: 24
#     end
#   end
# end

  Vagrant.configure("2") do |config|
    # Define the client {i} VM
    config.vm.define "client1" do |client|
      client.vm.hostname = "client1"
      client.vm.provider "docker" do |server_1|
        server_1.image = "datascientest:vagrant6"
        server_1.create_args = [
          "--cpuset-cpus=1",
          "--memory=1g"
        ]
      end
      client.vm.network "private_network", ip: "192.168.1.11", netmask: 24
    end
  end

    Vagrant.configure("2") do |config|
    # Define the client {i} VM
    config.vm.define "client2" do |client|
      client.vm.hostname = "client2"
      client.vm.provider "docker" do |server_1|
        server_1.image = "datascientest:vagrant6"
        server_1.create_args = [
          "--cpuset-cpus=1",
          "--memory=1g"
        ]
      end
      client.vm.network "private_network", ip: "192.168.1.12", netmask: 24
    end
  end

    Vagrant.configure("2") do |config|
    # Define the client {i} VM
    config.vm.define "client3" do |client|
      client.vm.hostname = "client3"
      client.vm.provider "docker" do |server_1|
        server_1.image = "datascientest:vagrant6"
        server_1.create_args = [
          "--cpuset-cpus=1",
          "--memory=1g"
        ]
      end
      client.vm.network "private_network", ip: "192.168.1.13", netmask: 24
    end
  end

    Vagrant.configure("2") do |config|
    # Define the client {i} VM
    config.vm.define "client4" do |client|
      client.vm.hostname = "client4"
      client.vm.provider "docker" do |server_1|
        server_1.image = "datascientest:vagrant6"
        server_1.create_args = [
          "--cpuset-cpus=1",
          "--memory=1g"
        ]
      end
      client.vm.network "private_network", ip: "192.168.1.14", netmask: 24
    end
  end